### ISSUE TITLE
Enhance `shellcheck` and `checkbashisms` CI to automatically include all relevant files

### ISSUE THREAD

**Issue by arthurbdiniz** [curl/wcurl#38]
## Description

Currently, the `shellcheck` and `checkbashisms` step in `.github/workflows/test.yml` explicitly lists files to check:

```yaml
- name: Run shellcheck
    run: shellcheck wcurl tests/*

- name: Run checkbashisms
    run: checkbashisms wcurl tests/*
```

This approach requires manual updates whenever files are `added`, `renamed`, or `moved`, which can lead to omissions in CI checks.

To improve maintainability, the workflow should dynamically include all relevant files without hardcoding their paths. There is related discussion on this topic in [koalaman/shellcheck#143](https://github.com/koalaman/shellcheck/issues/143).

## Tasks

1. Research dynamic file inclusion methods compatible with `shellcheck` and `checkbashisms`.
2. Update the workflow to automate file discovery.
3. Test the updated workflow to ensure all relevant files are checked.
4. Create a pull request with the enhanced configuration.

## Outcome

This enhancement will reduce maintenance overhead and ensure comprehensive CI checks for shell scripts.
